POST /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "fullname": "Vincentius",
    "email": "vincent@mail.com",
    "password": "123456"
}

###

POST /users/login HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "vincent@mail.com",
    "password": "123456"
}

###
PATCH /users/1/upload HTTP/1.1
Host: localhost:8888
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="profile_image"; filename="avatar.jpg"
Content-Type: image/jpeg

< /home/vincentius31/Pictures/Identity/Passport-Photos.jpeg
--WebBoundary--

###

GET /users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

###

GET /users/1 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

###

PUT /users/2 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "password": "kodathebest"
}

###

DELETE /users/2 HTTP/1.1
Host: localhost:8888
Content-Type: application/json


